
----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.152s

OK
/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py:87: DeprecationWarning: sign() is deprecated. Use the equivalent APIs in cryptography.
  sign = crypto.sign(signing_key, message.encode("utf-8"), 'SHA256')
EEEE...EEE.........FE..........EE...............E
======================================================================
ERROR: test_auth_header_when_uri_created_with_encoded_params (tests.test_oauth.OAuthTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/e142756/work/oauth1-signer-python/tests/test_oauth.py", line 362, in test_auth_header_when_uri_created_with_encoded_params
    auth_header = OAuth.get_authorization_header(url,
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 38, in get_authorization_header
    oauth_parameters = OAuth.get_oauth_parameters(uri, method, payload, consumer_key, signing_key)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 70, in get_oauth_parameters
    signature = OAuth.sign_message(base_string, signing_key)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 87, in sign_message
    sign = crypto.sign(signing_key, message.encode("utf-8"), 'SHA256')
  File "/Users/e142756/Library/Python/3.9/lib/python/site-packages/OpenSSL/crypto.py", line 3150, in sign
    length = _lib.EVP_PKEY_size(pkey._pkey)
AttributeError: 'cryptography.hazmat.bindings._rust.openssl.rsa.RSA' object has no attribute '_pkey'

======================================================================
ERROR: test_auth_header_when_uri_created_with_non_encoded_params (tests.test_oauth.OAuthTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/e142756/work/oauth1-signer-python/tests/test_oauth.py", line 397, in test_auth_header_when_uri_created_with_non_encoded_params
    auth_header = OAuth.get_authorization_header(url,
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 38, in get_authorization_header
    oauth_parameters = OAuth.get_oauth_parameters(uri, method, payload, consumer_key, signing_key)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 70, in get_oauth_parameters
    signature = OAuth.sign_message(base_string, signing_key)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 87, in sign_message
    sign = crypto.sign(signing_key, message.encode("utf-8"), 'SHA256')
  File "/Users/e142756/Library/Python/3.9/lib/python/site-packages/OpenSSL/crypto.py", line 3150, in sign
    length = _lib.EVP_PKEY_size(pkey._pkey)
AttributeError: 'cryptography.hazmat.bindings._rust.openssl.rsa.RSA' object has no attribute '_pkey'

======================================================================
ERROR: test_auth_header_when_uri_created_with_non_encoded_params_2 (tests.test_oauth.OAuthTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/e142756/work/oauth1-signer-python/tests/test_oauth.py", line 415, in test_auth_header_when_uri_created_with_non_encoded_params_2
    auth_header = OAuth.get_authorization_header(url,
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 38, in get_authorization_header
    oauth_parameters = OAuth.get_oauth_parameters(uri, method, payload, consumer_key, signing_key)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 70, in get_oauth_parameters
    signature = OAuth.sign_message(base_string, signing_key)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 87, in sign_message
    sign = crypto.sign(signing_key, message.encode("utf-8"), 'SHA256')
  File "/Users/e142756/Library/Python/3.9/lib/python/site-packages/OpenSSL/crypto.py", line 3150, in sign
    length = _lib.EVP_PKEY_size(pkey._pkey)
AttributeError: 'cryptography.hazmat.bindings._rust.openssl.rsa.RSA' object has no attribute '_pkey'

======================================================================
ERROR: test_backward_compatibility_with_static_method (tests.test_oauth.OAuthTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/e142756/work/oauth1-signer-python/tests/test_oauth.py", line 327, in test_backward_compatibility_with_static_method
    header = OAuth().get_authorization_header(OAuthTest.uri, 'POST', 'payload', 'dummy', OAuthTest.signing_key)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 38, in get_authorization_header
    oauth_parameters = OAuth.get_oauth_parameters(uri, method, payload, consumer_key, signing_key)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 70, in get_oauth_parameters
    signature = OAuth.sign_message(base_string, signing_key)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 87, in sign_message
    sign = crypto.sign(signing_key, message.encode("utf-8"), 'SHA256')
  File "/Users/e142756/Library/Python/3.9/lib/python/site-packages/OpenSSL/crypto.py", line 3150, in sign
    length = _lib.EVP_PKEY_size(pkey._pkey)
AttributeError: 'cryptography.hazmat.bindings._rust.openssl.rsa.RSA' object has no attribute '_pkey'

======================================================================
ERROR: test_get_authorization_header_nominal (tests.test_oauth.OAuthTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/e142756/work/oauth1-signer-python/tests/test_oauth.py", line 45, in test_get_authorization_header_nominal
    header = OAuth.get_authorization_header(OAuthTest.uri, 'POST', 'payload', 'dummy', OAuthTest.signing_key)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 38, in get_authorization_header
    oauth_parameters = OAuth.get_oauth_parameters(uri, method, payload, consumer_key, signing_key)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 70, in get_oauth_parameters
    signature = OAuth.sign_message(base_string, signing_key)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 87, in sign_message
    sign = crypto.sign(signing_key, message.encode("utf-8"), 'SHA256')
  File "/Users/e142756/Library/Python/3.9/lib/python/site-packages/OpenSSL/crypto.py", line 3150, in sign
    length = _lib.EVP_PKEY_size(pkey._pkey)
AttributeError: 'cryptography.hazmat.bindings._rust.openssl.rsa.RSA' object has no attribute '_pkey'

======================================================================
ERROR: test_get_authorization_header_should_compute_body_hash (tests.test_oauth.OAuthTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/e142756/work/oauth1-signer-python/tests/test_oauth.py", line 50, in test_get_authorization_header_should_compute_body_hash
    header = OAuth.get_authorization_header(OAuthTest.uri, 'POST', '{}', 'dummy', OAuthTest.signing_key)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 38, in get_authorization_header
    oauth_parameters = OAuth.get_oauth_parameters(uri, method, payload, consumer_key, signing_key)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 70, in get_oauth_parameters
    signature = OAuth.sign_message(base_string, signing_key)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 87, in sign_message
    sign = crypto.sign(signing_key, message.encode("utf-8"), 'SHA256')
  File "/Users/e142756/Library/Python/3.9/lib/python/site-packages/OpenSSL/crypto.py", line 3150, in sign
    length = _lib.EVP_PKEY_size(pkey._pkey)
AttributeError: 'cryptography.hazmat.bindings._rust.openssl.rsa.RSA' object has no attribute '_pkey'

======================================================================
ERROR: test_get_authorization_header_should_return_empty_string_body_hash (tests.test_oauth.OAuthTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/e142756/work/oauth1-signer-python/tests/test_oauth.py", line 54, in test_get_authorization_header_should_return_empty_string_body_hash
    header = OAuth.get_authorization_header(OAuthTest.uri, 'GET', None, 'dummy', OAuthTest.signing_key)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 38, in get_authorization_header
    oauth_parameters = OAuth.get_oauth_parameters(uri, method, payload, consumer_key, signing_key)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 70, in get_oauth_parameters
    signature = OAuth.sign_message(base_string, signing_key)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 87, in sign_message
    sign = crypto.sign(signing_key, message.encode("utf-8"), 'SHA256')
  File "/Users/e142756/Library/Python/3.9/lib/python/site-packages/OpenSSL/crypto.py", line 3150, in sign
    length = _lib.EVP_PKEY_size(pkey._pkey)
AttributeError: 'cryptography.hazmat.bindings._rust.openssl.rsa.RSA' object has no attribute '_pkey'

======================================================================
ERROR: test_oauth_parameters (tests.test_oauth.OAuthTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/e142756/work/oauth1-signer-python/tests/test_oauth.py", line 84, in test_oauth_parameters
    parameters = OAuth.get_oauth_parameters(uri, method, 'payload', 'dummy', OAuthTest.signing_key)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 70, in get_oauth_parameters
    signature = OAuth.sign_message(base_string, signing_key)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 87, in sign_message
    sign = crypto.sign(signing_key, message.encode("utf-8"), 'SHA256')
  File "/Users/e142756/Library/Python/3.9/lib/python/site-packages/OpenSSL/crypto.py", line 3150, in sign
    length = _lib.EVP_PKEY_size(pkey._pkey)
AttributeError: 'cryptography.hazmat.bindings._rust.openssl.rsa.RSA' object has no attribute '_pkey'

======================================================================
ERROR: test_sign_message (tests.test_oauth.OAuthTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/e142756/work/oauth1-signer-python/tests/test_oauth.py", line 71, in test_sign_message
    signature = OAuth.sign_message(base_string, OAuthTest.signing_key)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 87, in sign_message
    sign = crypto.sign(signing_key, message.encode("utf-8"), 'SHA256')
  File "/Users/e142756/Library/Python/3.9/lib/python/site-packages/OpenSSL/crypto.py", line 3150, in sign
    length = _lib.EVP_PKEY_size(pkey._pkey)
AttributeError: 'cryptography.hazmat.bindings._rust.openssl.rsa.RSA' object has no attribute '_pkey'

======================================================================
ERROR: test_sign_signature_base_string (tests.test_oauth.OAuthTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/e142756/work/oauth1-signer-python/tests/test_oauth.py", line 219, in test_sign_signature_base_string
    signing_string = OAuth.sign_message("baseString", OAuthTest.signing_key)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 87, in sign_message
    sign = crypto.sign(signing_key, message.encode("utf-8"), 'SHA256')
  File "/Users/e142756/Library/Python/3.9/lib/python/site-packages/OpenSSL/crypto.py", line 3150, in sign
    length = _lib.EVP_PKEY_size(pkey._pkey)
AttributeError: 'cryptography.hazmat.bindings._rust.openssl.rsa.RSA' object has no attribute '_pkey'

======================================================================
ERROR: test_valid_oauth_signature_with_percent (tests.test_oauth.OAuthTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/e142756/work/oauth1-signer-python/tests/test_oauth.py", line 345, in test_valid_oauth_signature_with_percent
    auth_header = OAuth.get_authorization_header('https://api.mastercard.com/abc/%123/service?a=123&b=%2a2b3',
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 38, in get_authorization_header
    oauth_parameters = OAuth.get_oauth_parameters(uri, method, payload, consumer_key, signing_key)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 70, in get_oauth_parameters
    signature = OAuth.sign_message(base_string, signing_key)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 87, in sign_message
    sign = crypto.sign(signing_key, message.encode("utf-8"), 'SHA256')
  File "/Users/e142756/Library/Python/3.9/lib/python/site-packages/OpenSSL/crypto.py", line 3150, in sign
    length = _lib.EVP_PKEY_size(pkey._pkey)
AttributeError: 'cryptography.hazmat.bindings._rust.openssl.rsa.RSA' object has no attribute '_pkey'

======================================================================
FAIL: test_nonce_uniqueness (tests.test_oauth.OAuthTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/e142756/work/oauth1-signer-python/tests/test_oauth.py", line 122, in test_nonce_uniqueness
    self.assertEqual(len(res), 0)
AssertionError: 1 != 0

----------------------------------------------------------------------
Ran 49 tests in 0.621s

FAILED (failures=1, errors=11)
/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py:87: DeprecationWarning: sign() is deprecated. Use the equivalent APIs in cryptography.
  sign = crypto.sign(signing_key, message.encode("utf-8"), 'SHA256')
EEEEEEEE.
======================================================================
ERROR: test_call (tests.test_oauth_ext.OAuthExtTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/e142756/work/oauth1-signer-python/tests/test_oauth_ext.py", line 147, in test_call
    call_object = oauth_object.__call__(OAuthExtTest.mock_prepared_request)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth_ext.py", line 55, in __call__
    OAuth.get_authorization_header(uri=r.url,
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 38, in get_authorization_header
    oauth_parameters = OAuth.get_oauth_parameters(uri, method, payload, consumer_key, signing_key)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 70, in get_oauth_parameters
    signature = OAuth.sign_message(base_string, signing_key)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 87, in sign_message
    sign = crypto.sign(signing_key, message.encode("utf-8"), 'SHA256')
  File "/Users/e142756/Library/Python/3.9/lib/python/site-packages/OpenSSL/crypto.py", line 3150, in sign
    length = _lib.EVP_PKEY_size(pkey._pkey)
AttributeError: 'cryptography.hazmat.bindings._rust.openssl.rsa.RSA' object has no attribute '_pkey'

======================================================================
ERROR: test_ext_oauth_header_equals_to_non_ext_generated (tests.test_oauth_ext.OAuthExtTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/e142756/work/oauth1-signer-python/tests/test_oauth_ext.py", line 155, in test_ext_oauth_header_equals_to_non_ext_generated
    call_object = oauth_object(OAuthExtTest.mock_prepared_request)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth_ext.py", line 55, in __call__
    OAuth.get_authorization_header(uri=r.url,
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 38, in get_authorization_header
    oauth_parameters = OAuth.get_oauth_parameters(uri, method, payload, consumer_key, signing_key)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 70, in get_oauth_parameters
    signature = OAuth.sign_message(base_string, signing_key)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 87, in sign_message
    sign = crypto.sign(signing_key, message.encode("utf-8"), 'SHA256')
  File "/Users/e142756/Library/Python/3.9/lib/python/site-packages/OpenSSL/crypto.py", line 3150, in sign
    length = _lib.EVP_PKEY_size(pkey._pkey)
AttributeError: 'cryptography.hazmat.bindings._rust.openssl.rsa.RSA' object has no attribute '_pkey'

======================================================================
ERROR: test_oauth_body_hash_with_body_bytes (tests.test_oauth_ext.OAuthExtTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/e142756/work/oauth1-signer-python/tests/test_oauth_ext.py", line 66, in test_oauth_body_hash_with_body_bytes
    oauth_object(OAuthExtTest.mock_prepared_request)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth_ext.py", line 55, in __call__
    OAuth.get_authorization_header(uri=r.url,
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 38, in get_authorization_header
    oauth_parameters = OAuth.get_oauth_parameters(uri, method, payload, consumer_key, signing_key)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 70, in get_oauth_parameters
    signature = OAuth.sign_message(base_string, signing_key)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 87, in sign_message
    sign = crypto.sign(signing_key, message.encode("utf-8"), 'SHA256')
  File "/Users/e142756/Library/Python/3.9/lib/python/site-packages/OpenSSL/crypto.py", line 3150, in sign
    length = _lib.EVP_PKEY_size(pkey._pkey)
AttributeError: 'cryptography.hazmat.bindings._rust.openssl.rsa.RSA' object has no attribute '_pkey'

======================================================================
ERROR: test_oauth_body_hash_with_body_empty (tests.test_oauth_ext.OAuthExtTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/e142756/work/oauth1-signer-python/tests/test_oauth_ext.py", line 79, in test_oauth_body_hash_with_body_empty
    oauth_object(OAuthExtTest.mock_prepared_request)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth_ext.py", line 55, in __call__
    OAuth.get_authorization_header(uri=r.url,
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 38, in get_authorization_header
    oauth_parameters = OAuth.get_oauth_parameters(uri, method, payload, consumer_key, signing_key)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 70, in get_oauth_parameters
    signature = OAuth.sign_message(base_string, signing_key)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 87, in sign_message
    sign = crypto.sign(signing_key, message.encode("utf-8"), 'SHA256')
  File "/Users/e142756/Library/Python/3.9/lib/python/site-packages/OpenSSL/crypto.py", line 3150, in sign
    length = _lib.EVP_PKEY_size(pkey._pkey)
AttributeError: 'cryptography.hazmat.bindings._rust.openssl.rsa.RSA' object has no attribute '_pkey'

======================================================================
ERROR: test_oauth_body_hash_with_body_empty_or_none (tests.test_oauth_ext.OAuthExtTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/e142756/work/oauth1-signer-python/tests/test_oauth_ext.py", line 115, in test_oauth_body_hash_with_body_empty_or_none
    oauth_object(request_empty)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth_ext.py", line 55, in __call__
    OAuth.get_authorization_header(uri=r.url,
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 38, in get_authorization_header
    oauth_parameters = OAuth.get_oauth_parameters(uri, method, payload, consumer_key, signing_key)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 70, in get_oauth_parameters
    signature = OAuth.sign_message(base_string, signing_key)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 87, in sign_message
    sign = crypto.sign(signing_key, message.encode("utf-8"), 'SHA256')
  File "/Users/e142756/Library/Python/3.9/lib/python/site-packages/OpenSSL/crypto.py", line 3150, in sign
    length = _lib.EVP_PKEY_size(pkey._pkey)
AttributeError: 'cryptography.hazmat.bindings._rust.openssl.rsa.RSA' object has no attribute '_pkey'

======================================================================
ERROR: test_oauth_body_hash_with_body_multipart (tests.test_oauth_ext.OAuthExtTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/e142756/work/oauth1-signer-python/tests/test_oauth_ext.py", line 136, in test_oauth_body_hash_with_body_multipart
    oauth_object(mock_request)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth_ext.py", line 55, in __call__
    OAuth.get_authorization_header(uri=r.url,
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 38, in get_authorization_header
    oauth_parameters = OAuth.get_oauth_parameters(uri, method, payload, consumer_key, signing_key)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 70, in get_oauth_parameters
    signature = OAuth.sign_message(base_string, signing_key)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 87, in sign_message
    sign = crypto.sign(signing_key, message.encode("utf-8"), 'SHA256')
  File "/Users/e142756/Library/Python/3.9/lib/python/site-packages/OpenSSL/crypto.py", line 3150, in sign
    length = _lib.EVP_PKEY_size(pkey._pkey)
AttributeError: 'cryptography.hazmat.bindings._rust.openssl.rsa.RSA' object has no attribute '_pkey'

======================================================================
ERROR: test_oauth_body_hash_with_body_none (tests.test_oauth_ext.OAuthExtTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/e142756/work/oauth1-signer-python/tests/test_oauth_ext.py", line 92, in test_oauth_body_hash_with_body_none
    oauth_object(OAuthExtTest.mock_prepared_request)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth_ext.py", line 55, in __call__
    OAuth.get_authorization_header(uri=r.url,
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 38, in get_authorization_header
    oauth_parameters = OAuth.get_oauth_parameters(uri, method, payload, consumer_key, signing_key)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 70, in get_oauth_parameters
    signature = OAuth.sign_message(base_string, signing_key)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 87, in sign_message
    sign = crypto.sign(signing_key, message.encode("utf-8"), 'SHA256')
  File "/Users/e142756/Library/Python/3.9/lib/python/site-packages/OpenSSL/crypto.py", line 3150, in sign
    length = _lib.EVP_PKEY_size(pkey._pkey)
AttributeError: 'cryptography.hazmat.bindings._rust.openssl.rsa.RSA' object has no attribute '_pkey'

======================================================================
ERROR: test_oauth_body_hash_with_body_string (tests.test_oauth_ext.OAuthExtTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/e142756/work/oauth1-signer-python/tests/test_oauth_ext.py", line 57, in test_oauth_body_hash_with_body_string
    oauth_object(OAuthExtTest.mock_prepared_request)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth_ext.py", line 55, in __call__
    OAuth.get_authorization_header(uri=r.url,
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 38, in get_authorization_header
    oauth_parameters = OAuth.get_oauth_parameters(uri, method, payload, consumer_key, signing_key)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 70, in get_oauth_parameters
    signature = OAuth.sign_message(base_string, signing_key)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 87, in sign_message
    sign = crypto.sign(signing_key, message.encode("utf-8"), 'SHA256')
  File "/Users/e142756/Library/Python/3.9/lib/python/site-packages/OpenSSL/crypto.py", line 3150, in sign
    length = _lib.EVP_PKEY_size(pkey._pkey)
AttributeError: 'cryptography.hazmat.bindings._rust.openssl.rsa.RSA' object has no attribute '_pkey'

----------------------------------------------------------------------
Ran 9 tests in 0.004s

FAILED (errors=8)
/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py:87: DeprecationWarning: sign() is deprecated. Use the equivalent APIs in cryptography.
  sign = crypto.sign(signing_key, message.encode("utf-8"), 'SHA256')
EE
======================================================================
ERROR: test_sign_prepared_request (tests.test_signer.SignerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/mock.py", line 1337, in patched
    return func(*newargs, **newkeywargs)
  File "/Users/e142756/work/oauth1-signer-python/tests/test_signer.py", line 67, in test_sign_prepared_request
    requests.get(SignerTest.uri, auth=signer)
  File "/Users/e142756/Library/Python/3.9/lib/python/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/e142756/Library/Python/3.9/lib/python/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/e142756/Library/Python/3.9/lib/python/site-packages/requests/sessions.py", line 515, in request
    prep = self.prepare_request(req)
  File "/Users/e142756/Library/Python/3.9/lib/python/site-packages/requests/sessions.py", line 443, in prepare_request
    p.prepare(
  File "/Users/e142756/Library/Python/3.9/lib/python/site-packages/requests/models.py", line 322, in prepare
    self.prepare_auth(auth, url)
  File "/Users/e142756/Library/Python/3.9/lib/python/site-packages/requests/models.py", line 558, in prepare_auth
    r = auth(self)
  File "/Users/e142756/work/oauth1-signer-python/tests/test_signer.py", line 63, in __call__
    self.signer.sign_request(request.url, request)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/signer.py", line 42, in sign_request
    oauth_key = OAuth.get_authorization_header(uri, request.method, body, self.consumer_key,
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 38, in get_authorization_header
    oauth_parameters = OAuth.get_oauth_parameters(uri, method, payload, consumer_key, signing_key)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 70, in get_oauth_parameters
    signature = OAuth.sign_message(base_string, signing_key)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 87, in sign_message
    sign = crypto.sign(signing_key, message.encode("utf-8"), 'SHA256')
  File "/Users/e142756/Library/Python/3.9/lib/python/site-packages/OpenSSL/crypto.py", line 3150, in sign
    length = _lib.EVP_PKEY_size(pkey._pkey)
AttributeError: 'cryptography.hazmat.bindings._rust.openssl.rsa.RSA' object has no attribute '_pkey'

======================================================================
ERROR: test_sign_request (tests.test_signer.SignerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/e142756/work/oauth1-signer-python/tests/test_signer.py", line 51, in test_sign_request
    request = signer.sign_request(SignerTest.uri, request)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/signer.py", line 42, in sign_request
    oauth_key = OAuth.get_authorization_header(uri, request.method, body, self.consumer_key,
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 38, in get_authorization_header
    oauth_parameters = OAuth.get_oauth_parameters(uri, method, payload, consumer_key, signing_key)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 70, in get_oauth_parameters
    signature = OAuth.sign_message(base_string, signing_key)
  File "/Users/e142756/work/oauth1-signer-python/oauth1/oauth.py", line 87, in sign_message
    sign = crypto.sign(signing_key, message.encode("utf-8"), 'SHA256')
  File "/Users/e142756/Library/Python/3.9/lib/python/site-packages/OpenSSL/crypto.py", line 3150, in sign
    length = _lib.EVP_PKEY_size(pkey._pkey)
AttributeError: 'cryptography.hazmat.bindings._rust.openssl.rsa.RSA' object has no attribute '_pkey'

----------------------------------------------------------------------
Ran 2 tests in 0.004s

FAILED (errors=2)
.
----------------------------------------------------------------------
Ran 1 test in 0.153s

OK
